config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  resources :users, only: [:show, :edit, :update], param: :display_name
  resources :topics, only: [:index, :show], param: :display_name
  resources :countries, only: [:index, :show], param: :display_name
  resources :indicators, only: [:index, :show], param: :display_name
  resources :visuals, only: [:show], param: :display_name
  resources :previews, only: [:index, :show], param: :display_name

  namespace :admin do
    resources :users, param: :display_name
    resources :topics, param: :display_name
    resources :tags, only: [:new, :create, :index, :destroy]
    resources :countries, param: :display_name
    resources :indicators, param: :display_name
    resources :visuals, param: :display_name
    resources :previews, param: :display_name
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :country_tags, dependent: :delete_all
  has_many :tags, through: :country_tags
  has_many :topic_countries, dependent: :delete_all
  has_many :topics, through: :topic_countries
  has_many :country_visuals, dependent: :delete_all
  has_many :visuals, through: :country_visuals
  has_many :country_indicators, dependent: :delete_all
  has_many :indicators, through: :country_indicators
  has_many :preview_countries, dependent: :delete_all
  has_many :previews, through: :preview_countries

  accepts_nested_attributes_for :visuals

  validates :name, presence: true, uniqueness: true
  validates_presence_of :last_updated

  def to_param
    display_name
  end
end

app/models/country_tag.rb
class CountryTag < ActiveRecord::Base
  belongs_to :country
  belongs_to :tag
end

app/models/country_visual.rb
class CountryVisual < ActiveRecord::Base
  belongs_to :country
  belongs_to :visual
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :topic
  belongs_to :visual
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :indicator_tags, dependent: :delete_all
  has_many :tags, through: :indicator_tags
  has_many :indicator_visuals, dependent: :delete_all
  has_many :visuals, through: :indicator_visuals
  has_many :topic_indicators, dependent: :delete_all
  has_many :topics, through: :topic_indicators
  has_many :country_indicators, dependent: :delete_all
  has_many :countries, through: :country_indicators
  has_many :preview_indicators, dependent: :delete_all
  has_many :previews, through: :preview_indicators

  accepts_nested_attributes_for :visuals

  validates :name, presence: true
  validates_presence_of :last_updated

  def to_param
    display_name
  end
end

app/models/indicator_tag.rb
class IndicatorTag < ActiveRecord::Base
  belongs_to :indicator
  belongs_to :tag
end

app/models/indicator_visual.rb
class IndicatorVisual < ActiveRecord::Base
  belongs_to :indicator
  belongs_to :visual
end

app/models/preview.rb
class Preview < ActiveRecord::Base
  has_many :preview_tags, dependent: :delete_all
  has_many :tags, through: :preview_tags
  has_many :preview_visuals, dependent: :delete_all
  has_many :visuals, through: :preview_visuals
  has_many :preview_topics, dependent: :delete_all
  has_many :topics, through: :preview_topics
  has_many :preview_countries, dependent: :delete_all
  has_many :countries, through: :preview_countries
  has_many :preview_indicators, dependent: :delete_all
  has_many :indicators, through: :preview_indicators

  accepts_nested_attributes_for :visuals

  validates :title, presence: true, uniqueness: true
  validates_presence_of :report_date

  def to_param
    display_name
  end

  def find_related_previews
    if self.tags.any?
      self.tags.sort_by{ |tag| tag.previews.count }.last.previews.reject{ |preview| preview.title == self.title }.sort_by(&:updated_at).last(2).reverse!
    else
      []
    end
  end
end

app/models/preview_country.rb
class PreviewCountry < ActiveRecord::Base
  belongs_to :preview
  belongs_to :country
end

app/models/preview_tag.rb
class PreviewTag < ActiveRecord::Base
  belongs_to :preview
  belongs_to :tag
end

app/models/preview_topic.rb
class PreviewTopic < ActiveRecord::Base
  belongs_to :preview
  belongs_to :topic
end

app/models/preview_visual.rb
class PreviewVisual < ActiveRecord::Base
  belongs_to :preview
  belongs_to :visual
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :topic_tags, dependent: :delete_all
  has_many :topics, through: :topic_tags

  has_many :indicator_tags, dependent: :delete_all
  has_many :indicators, through: :indicator_tags

  has_many :country_tags, dependent: :delete_all
  has_many :countries, through: :country_tags

  has_many :preview_tags, dependent: :delete_all
  has_many :previews, through: :preview_tags

  validates :name, presence: true, uniqueness: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :topic_tags, dependent: :delete_all
  has_many :tags, through: :topic_tags
  has_many :topic_visuals, dependent: :delete_all
  has_many :visuals, through: :topic_visuals
  has_many :topic_indicators, dependent: :delete_all
  has_many :indicators, through: :topic_indicators
  has_many :topic_countries, dependent: :delete_all
  has_many :countries, through: :topic_countries
  has_many :preview_topics, dependent: :delete_all
  has_many :previews, through: :preview_topics

  accepts_nested_attributes_for :visuals

  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :report_date

  def to_param
    display_name
  end
end

app/models/topic_country.rb
class TopicCountry < ActiveRecord::Base
  belongs_to :topic
  belongs_to :country
end

app/models/topic_indicator.rb
class TopicIndicator < ActiveRecord::Base
  belongs_to :topic
  belongs_to :indicator
end

app/models/topic_tag.rb
class TopicTag < ActiveRecord::Base
  belongs_to :topic
  belongs_to :tag
end

app/models/topic_visual.rb
class TopicVisual < ActiveRecord::Base
  belongs_to :topic
  belongs_to :visual
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :role, presence: true

  enum role: %w(default admin)

  def to_param
    display_name
  end
end

app/models/visual.rb
class Visual < ActiveRecord::Base
  has_many :topic_visuals, dependent: :delete_all
  has_many :topics, through: :topic_visuals
  has_many :country_visuals, dependent: :delete_all
  has_many :countries, through: :country_visuals
  has_many :indicator_visuals, dependent: :delete_all
  has_many :indicators, through: :indicator_visuals
  has_many :preview_visuals, dependent: :delete_all
  has_many :previews, through: :preview_visuals

  validates_presence_of :title
  validates_presence_of :link

  def to_param
    display_name
  end

  def find_visual_source_name
    if self.countries.any?
      self.countries.first.name
    elsif self.topics.any?
      self.topics.first.title
    elsif self.indicators.any?
      self.indicators.first.name + " (" + self.indicators.first.countries.first.name + ")"
    elsif self.previews.any?
      self.previews.first.title
    end
  end

  def find_visual_source_type
    if self.countries.any?
      "Country"
    elsif self.topics.any?
      "Topic"
    elsif self.indicators.any?
      "Indicator"
    elsif self.previews.any?
      "Preview"
    end
  end

  def find_visual_source_route
    if self.countries.any?
      "/countries/" + self.countries.first.display_name
    elsif self.topics.any?
      "/topics/" + self.topics.first.display_name
    elsif self.indicators.any?
      "/indicators/" + self.indicators.first.display_name
    elsif self.previews.any?
      "/previews/" + self.previews.first.display_name
    end
  end

  def find_admin_visual_source_route
    if self.countries.any?
      "/admin/countries/" + self.countries.first.display_name
    elsif self.topics.any?
      "/admin/topics/" + self.topics.first.display_name
    elsif self.indicators.any?
      "/admin/indicators/" + self.indicators.first.display_name
    elsif self.previews.any?
      "/admin/previews/" + self.previews.first.display_name
    end
  end
end

app/controllers/admin/landing_controller.rb
class Admin::LandingController < Admin::BaseController
  def show
  end

  def index
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
  end

  def index
    @first_preview = Preview.find_by(title: "Emerging Markets Debt")
    @second_preview = Preview.find_by(title: "The Global Oil Market")
    @third_preview = Preview.find_by(title: "Emerging Markets Debt")
  end
end

app/views/landing/index.html.erb
<body cz-shortcut-listen="true">

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" id="cidot1" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" id="cidot2" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" id="cidot3" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img id="slide-image" class="first-slide" src="/images/em-debt-cover-pic.png" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="slide-title"><%= @first_preview.title %></h1>
              <% if current_admin? %>
                <p><%= link_to "View report", admin_preview_path(@first_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% else %>
                <p><%= link_to "View report", preview_path(@first_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="item">
          <img id="slide-image" class="second-slide" src="/images/oil3.png" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="slide-title"><%= @second_preview.title %></h1>
              <% if current_admin? %>
                <p><%= link_to "View report", admin_preview_path(@second_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% else %>
                <p><%= link_to "View report", preview_path(@second_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="item">
          <img id="slide-image" class="third-slide" src="/images/em-debt-cover-pic.png" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="slide-title"><%= @third_preview.title %></h1>
              <% if current_admin? %>
                <p><%= link_to "View report", admin_preview_path(@third_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% else %>
                <p><%= link_to "View report", preview_path(@third_preview), class: "btn btn-lg btn-primary landing", role: "button" %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</body>