config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  resources :users, only: [:show, :edit, :update], param: :display_name
  resources :topics, only: [:index, :show], param: :display_name
  resources :countries, only: [:index, :show], param: :display_name
  resources :indicators, only: [:index, :show], param: :display_name
  resources :visuals, only: [:show], param: :display_name
  resources :previews, only: [:index, :show], param: :display_name

  namespace :admin do
    resources :users, param: :display_name
    resources :topics, param: :display_name
    resources :tags, only: [:new, :create, :index, :destroy]
    resources :countries, param: :display_name
    resources :indicators, param: :display_name
    resources :visuals, param: :display_name
    resources :previews, param: :display_name
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :topic_tags, dependent: :delete_all
  has_many :tags, through: :topic_tags
  has_many :topic_visuals, dependent: :delete_all
  has_many :visuals, through: :topic_visuals
  has_many :topic_indicators, dependent: :delete_all
  has_many :indicators, through: :topic_indicators
  has_many :topic_countries, dependent: :delete_all
  has_many :countries, through: :topic_countries
  has_many :preview_topics, dependent: :delete_all
  has_many :previews, through: :preview_topics

  accepts_nested_attributes_for :visuals

  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :report_date

  def to_param
    display_name
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  before_action :require_login

  def index
    @topics = Topic.all.sort_by(&:updated_at).reverse!
  end

  def new
    @topic = Topic.new
    @visuals = @topic.visuals.build
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      @topic.update(display_name: SecureRandom.hex(5))
      create_topic_countries
      create_topic_indicators
      create_topic_tags
      create_visual_display_names
      redirect_to admin_topic_path(@topic)
    else
      flash[:error] = @topic.errors.full_messages.first
      render :action => 'new'
    end
  end

  def show
    @topic = Topic.find_by(display_name: params[:display_name])
    @visuals = @topic.visuals.sort
    @related_countries = @topic.countries
    @related_indicators = @topic.indicators
    @related_topics = @topic.tags.sort_by{ |tag| tag.topics.count }.last.topics.reject{ |topic| topic.title == @topic.title }.sort_by(&:updated_at).last(2).reverse!
  end

  def edit
    @topic = Topic.find_by(display_name: params[:display_name])
    @visuals = @topic.visuals.sort
  end

  def update
    @topic = Topic.find_by(display_name: params[:display_name])
    if @topic.update(topic_params)
      update_topic_countries
      update_topic_indicators
      update_topic_tags
      update_visual_display_names
      flash[:success] = "Topic was updated successfully!"
      redirect_to admin_topic_path(@topic)
    else
      flash[:error] = @topic.errors.full_messages.first
      redirect_to edit_admin_topic_path(@topic)
    end
  end

  def destroy
    topic = Topic.find_by(display_name: params[:display_name])
    topic.countries.clear
    topic.indicators.clear
    topic.tags.clear
    topic.visuals.each { |visual| visual.destroy }
    topic.destroy
    flash[:success] = "Topic deleted!"
    redirect_to admin_topics_path
  end

private
  def topic_params
    params.require(:topic).permit(:title, :report_date, :tagline, :intro, :conclusion, { visuals_attributes: [:id, :title, :intro, :link, :caption, :description]})
  end

  def create_topic_countries
    countries = params[:topic][:countries]
    countries.each do |country_id|
      if country_id != ""
        @topic.countries << Country.find_by(id: country_id)
      end
    end
  end

  def create_topic_indicators
    indicators = params[:topic][:indicators]
    indicators.each do |indicator_id|
      if indicator_id != ""
        @topic.indicators << Indicator.find_by(id: indicator_id)
      end
    end
  end

  def create_topic_tags
    tags = params[:topic][:tags]
    tags.each do |tag_id|
      if tag_id != ""
        @topic.tags << Tag.find_by(id: tag_id)
      end
    end
  end

  def create_visual_display_names
    @topic.visuals.each do |visual|
      visual.update(display_name: SecureRandom.hex(5))
    end
  end

  def update_topic_countries
    @topic.countries.clear
    countries = params[:topic][:countries]
    countries.each do |country_id|
      if country_id != ""
        @topic.countries << Country.find_by(id: country_id)
      end
    end
  end

  def update_topic_indicators
    @topic.indicators.clear
    indicators = params[:topic][:indicators]
    indicators.each do |indicator_id|
      if indicator_id != ""
        @topic.indicators << Indicator.find_by(id: indicator_id)
      end
    end
  end

  def update_topic_tags
    @topic.tags.clear
    tags = params[:topic][:tags]
    tags.each do |tag_id|
      if tag_id != ""
        @topic.tags << Tag.find_by(id: tag_id)
      end
    end
  end

  def update_visual_display_names
    @topic.visuals.each do |visual|
      if visual.display_name == nil
        visual.update(display_name: SecureRandom.hex(5))
      end
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_login

  def index
    @topics = Topic.all.sort_by(&:updated_at).reverse!
  end

  def show
    @topic = Topic.find_by(display_name: params[:display_name])
    @visuals = @topic.visuals.sort
    @related_countries = @topic.countries
    @related_indicators = @topic.indicators
    @related_topics = @topic.tags.sort_by{ |tag| tag.topics.count }.last.topics.reject{ |topic| topic.title == @topic.title }.sort_by(&:updated_at).last(2).reverse!
  end
end

app/views/topics/index.html.erb
<div class="container" id="topics-container">
  <h1 class="index-title"><span style="font-size: 25px;" class="glyphicon glyphicon-th-list"></span> Topics</h1>

  <% @topics.each do |topic| %>
    <h2 class="index-item-title"><%= link_to topic.title, topic_path(topic) %></h2>
    <h4><em><%= topic.report_date %></em></h4>
    <div class="tagline-index"><%= topic.tagline.html_safe %></div><hr>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="column col-xs-12">
      <div class="container" id="topic-container">
        <h4 style="color: #CCC; margin-top: 5px; margin-bottom: -9px;"><span class="glyphicon glyphicon-th-list"></span>&nbsp Topic</h4>

        <h1><%= @topic.title %></h1>
        <p style="font-size: 14px; margin-top: -5px; color: #888;"><%= @topic.report_date %></p>

        <% if @topic.tagline %>
          <div class="tagline">
            <%= @topic.tagline.html_safe %>
          </div>
        <% end %>

        <%= @topic.intro.html_safe %><br>
        <% @visuals.each do |visual| %>
          <h3 style="color: #777; margin-top: 16px;"><%= visual.title %></h3>
          <p style="margin-top: -3px; margin-bottom: 12px;"><%= visual.intro.html_safe %></p>
          <%= visual.link.html_safe %>
          <p class="visual-caption"><em><%= visual.caption %></em></p>
          <%= visual.description.html_safe %>
        <% end %>

        <h3>Conclusion</h3>
        <p><%= @topic.conclusion.html_safe %></p><hr>

        <h4><span class="glyphicon glyphicon-th-list"></span>&nbsp Related Topics</h4>
        <% @related_topics.each do |topic| %>
        <div id="related-topic">
          <h3 style="margin-top: 10px;"><%= link_to topic.title, topic_path(topic) %></h3>
          <em><h5 style="margin-top: -5px; margin-bottom: 5px; color: #888"><%= topic.report_date %></h5></em>
          <%= truncate(topic.intro.gsub("<p>", ""), length: 250) %>
        </div>
        <% end %><hr>

        <h4>Tags</h4>
        <ul>
          <% @topic.tags.each do |tag| %>
          <li><%= tag.name %></li>
          <% end %>
        </ul><br>
      </div>
    </div>

    <div class="column col-xs-3" id="sidebar">
      <div id="indicator-sidebar">
        <h4><span class="glyphicon glyphicon-eye-open"></span>&nbsp Visuals</h4>
        <table id="ind-side-table">
          <% @visuals.each do |visual| %>
          <tr>
            <td><%= link_to visual.title, visual_path(visual) %></td>
          </tr>
          <% end %>
        </table>
      </div>
      <div id="country-sidebar">
        <h4><span class="glyphicon glyphicon-globe"></span>&nbsp Related Countries</h4>
        <ul>
          <% @related_countries.each do |country| %>
          <li><%= link_to country.name, country_path(country) %></li>
          <% end %>
        </ul>
      </div>
      <div id="indicator-sidebar">
        <h4><span class="glyphicon glyphicon-stats"></span>&nbsp Related Indicators</h4>
        <ul>
          <% @related_indicators.each do |indicator| %>
            <li><%= link_to indicator.name + " (" + indicator.countries.first.name + ")", indicator_path(indicator) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>