config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  resources :users, only: [:show, :edit, :update], param: :display_name
  resources :topics, only: [:index, :show], param: :display_name
  resources :countries, only: [:index, :show], param: :display_name
  resources :indicators, only: [:index, :show], param: :display_name
  resources :visuals, only: [:show], param: :display_name
  resources :previews, only: [:index, :show], param: :display_name

  namespace :admin do
    resources :users, param: :display_name
    resources :topics, param: :display_name
    resources :tags, only: [:new, :create, :index, :destroy]
    resources :countries, param: :display_name
    resources :indicators, param: :display_name
    resources :visuals, param: :display_name
    resources :previews, param: :display_name
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'
end

app/controllers/admin/previews_controller.rb
class Admin::PreviewsController < Admin::BaseController
  before_action :require_login, except: [:show, :index]

  def index
    @previews = Preview.all.sort_by(&:updated_at).reverse!
  end

  def show
    @preview = Preview.find_by(display_name: params[:display_name])
    @visuals = @preview.visuals.sort
    @related_topics = @preview.topics.sort_by(&:updated_at).last(2).reverse!
    @related_countries = @preview.countries
    @related_indicators = @preview.indicators
  end

  def new
    @preview = Preview.new
    @visuals = @preview.visuals.build
  end

  def create
    @preview = Preview.new(preview_params)
    if @preview.save
      @preview.update(display_name: SecureRandom.hex(5))
      create_preview_topics
      create_preview_countries
      create_preview_indicators
      create_preview_tags
      create_visual_display_names
      redirect_to admin_preview_path(@preview)
    else
      flash[:error] = @preview.errors.full_messages.first
      render :action => 'new'
    end
  end

  def edit
    @preview = Preview.find_by(display_name: params[:display_name])
    @visuals = @preview.visuals.sort
  end

  def update
    @preview = Preview.find_by(display_name: params[:display_name])
    if @preview.update(preview_params)
      update_preview_topics
      update_preview_countries
      update_preview_indicators
      update_preview_tags
      update_visual_display_names
      flash[:success] = "Preview was updated successfully!"
      redirect_to admin_preview_path(@preview)
    else
      flash[:error] = @preview.errors.full_messages.first
      redirect_to edit_admin_preview_path(@preview)
    end
  end

  def destroy
    preview = Preview.find_by(display_name: params[:display_name])
    preview.topics.clear
    preview.countries.clear
    preview.indicators.clear
    preview.visuals.each { |visual| visual.destroy }
    preview.tags.clear
    preview.destroy
    flash[:success] = "Preview deleted!"
    redirect_to admin_previews_path
  end

private
  def preview_params
    params.require(:preview).permit(:title, :report_date, :tagline, :intro, :conclusion, { visuals_attributes: [:id, :title, :intro, :link, :caption, :description]})
  end

  def create_preview_topics
    topics = params[:preview][:topics]
    topics.each do |topic_id|
      if topic_id != ""
        @preview.topics << Topic.find_by(id: topic_id)
      end
    end
  end

  def create_preview_countries
    countries = params[:preview][:countries]
    countries.each do |country_id|
      if country_id != ""
        @preview.countries << Country.find_by(id: country_id)
      end
    end
  end

  def create_preview_indicators
    indicators = params[:preview][:indicators]
    indicators.each do |indicator_id|
      if indicator_id != ""
        @preview.indicators << Indicator.find_by(id: indicator_id)
      end
    end
  end

  def create_preview_tags
    tags = params[:preview][:tags]
    tags.each do |tag_id|
      if tag_id != ""
        @preview.tags << Tag.find_by(id: tag_id)
      end
    end
  end

  def create_visual_display_names
    @preview.visuals.each do |visual|
      visual.update(display_name: SecureRandom.hex(5))
    end
  end

  def update_preview_topics
    @preview.topics.clear
    topics = params[:preview][:topics]
    topics.each do |topic_id|
      if topic_id != ""
        @preview.topics << Topic.find_by(id: topic_id)
      end
    end
  end

  def update_preview_countries
    @preview.countries.clear
    countries = params[:preview][:countries]
    countries.each do |country_id|
      if country_id != ""
        @preview.countries << Country.find_by(id: country_id)
      end
    end
  end

  def update_preview_indicators
    @preview.indicators.clear
    indicators = params[:preview][:indicators]
    indicators.each do |indicator_id|
      if indicator_id != ""
        @preview.indicators << Indicator.find_by(id: indicator_id)
      end
    end
  end

  def update_preview_tags
    @preview.tags.clear
    tags = params[:preview][:tags]
    tags.each do |tag_id|
      if tag_id != ""
        @preview.tags << Tag.find_by(id: tag_id)
      end
    end
  end

  def update_visual_display_names
    @preview.visuals.each do |visual|
      if visual.display_name == nil
        visual.update(display_name: SecureRandom.hex(5))
      end
    end
  end
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  def index
    @previews = Preview.all.sort_by(&:updated_at).reverse!
  end

  def show
    @preview = Preview.find_by(display_name: params[:display_name])
    @visuals = @preview.visuals.sort
    @related_topics = @preview.topics.sort_by(&:updated_at).last(2).reverse!
    @related_previews = @preview.find_related_previews
  end
end

app/views/admin/previews/edit.html.erb
<div class="container" id="edit-preview-container">
  <%= link_to "Back to Preview", admin_preview_path(@preview), class: "back-to-link" %>

  <h1>Edit Preview</h1>

  <div class="add-visual-button-container">
    <%= button_to "Add Visual", "javascript:void(0)", class: "btn btn-control btn-primary", id: "preview-edit-add-visual-button" %><br>
  </div>

  <%= form_for [:admin, @preview], html: { class: "form-group" } do |f| %>
    <div class="default-preview-edit-items">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %><br>

      <%= f.label :report_date %>
      <%= f.text_field :report_date, class: "form-control" %><br>

      <%= f.label :tagline %>
      <%= f.text_area :tagline, class: "form-control", rows: 8 %><br>

      <%= f.label :intro %>
      <%= f.text_area :intro, class: "form-control", rows: 8 %><br>

      <%= f.fields_for :visuals, @visuals do |ff| %>
        <div class="preview-edit-page-visual-counter">
          <hr><%= ff.label :title %>
          <%= ff.text_field :title, class: "form-control" %><br>

          <%= ff.label :intro %>
          <%= ff.text_area :intro, class: "form-control", rows: 8 %><br>

          <%= ff.label :link %>
          <%= ff.text_field :link, class: "form-control" %><br>

          <%= ff.label :caption %>
          <%= ff.text_field :caption, class: "form-control" %><br>

          <%= ff.label :description %>
          <%= ff.text_area :description, class: "form-control", rows: 8 %><br>
        </div>
      <% end %>
    </div>

    <hr><%= f.label :conclusion %>
    <%= f.text_area :conclusion, class: "form-control", rows: 8 %><hr>

    <h4><span class="glyphicon glyphicon-globe"></span>&nbsp Related Topics</h4>
    <%= f.fields_for :topics do |topic| %>
      <%= collection_check_boxes :preview, :topics, Topic.all.sort_by(&:title), :id, :title do |b| %>
      <p>
        <%= b.check_box(class: "check_box", checked: @preview.topics.include?(Topic.find_by(display_name: b.object.display_name))) %>
        <%= b.object.title %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-globe"></span>&nbsp Related Countries</h4>
    <%= f.fields_for :countries do |country| %>
      <%= collection_check_boxes :preview, :countries, Country.all.sort_by(&:name), :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box", checked: @preview.countries.include?(Country.find_by(display_name: b.object.display_name))) %>
        <%= b.object.name %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-stats"></span>&nbsp Related Indicators</h4>
    <%= f.fields_for :indicators do |indicator| %>
      <%= collection_check_boxes :preview, :indicators, Indicator.all.sort_by {|indicator| indicator.countries.first.name}, :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box", checked: @preview.indicators.include?(Indicator.find_by(display_name: b.object.display_name))) %>
        <strong><%= b.object.countries.first.name %></strong> - <%= b.object.name %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-user"></span>&nbsp User Tags</h4>
    <%= f.fields_for :tags do |tag| %>
      <%= collection_check_boxes :preview, :tags, Tag.all, :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box", checked: @preview.tags.include?(Tag.find_by(display_name: b.object.display_name))) %>
        <%= b.object.name %>
      </p>
      <% end %>
    <% end %>

    <br><%= f.submit "Update preview", class: "btn btn-control btn-primary" %>
  <% end %>
</div>

app/views/admin/previews/index.html.erb
<div class="container" id="preview-index-container">
  <h1 class="index-title"><span style="font-size: 25px;" class="glyphicon glyphicon-zoom-in"></span> Previews</h1>

  <form method="GET" action="/admin/previews/new">
    <input type="submit" value="Create new preview", class="btn btn-control btn-success">
  </form>

  <% @previews.each do |preview| %>
    <h2 class="index-item-title"><%= link_to preview.title, admin_preview_path(preview) %></h2>
    <h4><em><%= preview.report_date %></em></h4>
    <div class="tagline-index"><%= preview.tagline.html_safe %></div><hr>
  <% end %>
</div>

app/views/admin/previews/new.html.erb
<div class="container" id="new-preview-container">
  <%= link_to "Back to Previews", admin_previews_path, class: "back-to-link" %>

  <h1>Create Preview</h1>

  <div class="add-visual-button-container">
    <%= button_to "Add Visual", "javascript:void(0)", class: "btn btn-control btn-primary", id: "preview-add-visual-button" %><br>
  </div>

  <%= form_for [:admin, @preview], html: { class: "form-group" } do |f| %>
    <div class="default-preview-items">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %><br>

      <%= f.label :report_date %>
      <%= f.text_field :report_date, class: "form-control", placeholder: "Enter report date" %><br>

      <%= f.label :tagline %>
      <%= f.text_area :tagline, class: "form-control", placeholder: "Enter key takeaways", rows: 8 %><br>

      <%= f.label :intro %>
      <%= f.text_area :intro, class: "form-control", placeholder: "Enter introduction (if applicable)", rows: 8 %><br><hr>

      <h4>Visual #1</h4>

      <%= f.fields_for :visuals do |ff| %>
        <%= ff.label :title %>
        <%= ff.text_field :title, class: "form-control", placeholder: "Enter title" %><br>

        <%= ff.label :intro %>
        <%= ff.text_area :intro, class: "form-control", placeholder: "Enter introduction or explanation of visual", rows: 8 %><br>

        <%= ff.label :link %>
        <%= ff.text_field :link, class: "form-control", placeholder: "Enter Tableau script or URL" %><br>

        <%= ff.label :caption %>
        <%= ff.text_field :caption, class: "form-control", placeholder: "Enter caption for visual" %><br>

        <%= ff.label :description %>
        <%= ff.text_area :description, class: "form-control", placeholder: "Enter description for visual and/or additional text", rows: 8 %><br><hr>
      <% end %>
    </div>

    <%= f.label :conclusion %>
    <%= f.text_area :conclusion, class: "form-control", placeholder: "Enter conclusion (if applicable)", rows: 8 %><hr>

    <h4><span class="glyphicon glyphicon-th-list"></span>&nbsp Related Topics</h4>
    <%= f.fields_for :topics do |topic| %>
      <%= collection_check_boxes :preview, :topics, Topic.all.sort_by(&:title), :id, :title do |b| %>
      <p>
        <%= b.check_box(class: "check_box") %>
        <%= b.object.title %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-globe"></span>&nbsp Related Countries</h4>
    <%= f.fields_for :countries do |country| %>
      <%= collection_check_boxes :preview, :countries, Country.all.sort_by(&:name), :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box") %>
        <%= b.object.name %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-stats"></span>&nbsp Related Indicators</h4>
    <%= f.fields_for :indicators do |indicator| %>
      <%= collection_check_boxes :preview, :indicators, Indicator.all.sort_by {|indicator| indicator.countries.first.name}, :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box") %>
        <strong><%= b.object.countries.first.name %></strong> - <%= b.object.name %>
      </p>
      <% end %>
    <% end %><hr>

    <h4><span class="glyphicon glyphicon-user"></span>&nbsp User Tags</h4>
    <%= f.fields_for :tags do |tag| %>
      <%= collection_check_boxes :preview, :tags, Tag.all, :id, :name do |b| %>
      <p>
        <%= b.check_box(class: "check_box") %>
        <%= b.object.name %>
      </p>
      <% end %>
    <% end %>

    <br><%= f.submit "Create preview", class: "btn btn-control btn-primary" %>
  <% end %>
</div>

app/views/admin/previews/show.html.erb
<div class="container">
  <div class="row">
    <div class="column col-xs-12">
      <div class="container" id="preview-container">
        <%= link_to "Back to Previews", admin_previews_path, class: "back-to-link" %>

        <h4 style="color: #CCC; margin-top: 16px; margin-bottom: -9px;"><span class="glyphicon glyphicon-zoom-in"></span>&nbsp Preview</h4>

        <h1><%= @preview.title %></h1>
        <p style="font-size: 16px; margin-top: -5px; color: #888;"><em><%= @preview.report_date %></em></p>

        <% if @preview.tagline %>
          <div class="tagline">
            <%= @preview.tagline.html_safe %>
          </div>
        <% end %>

        <span style="font-size: 15px;"><%= @preview.intro.html_safe %></span><br>
        <% @visuals.each do |visual| %>
          <h3 style="color: #777; margin-top: 16px;"><%= visual.title %></h3>
          <p style="margin-top: -3px; margin-bottom: 12px;"><%= visual.intro.html_safe %></p>
          <%= visual.link.html_safe %>
          <p class="visual-caption"><em><%= visual.caption %></em></p>
          <%= visual.description.html_safe %>
        <% end %>

        <h3>Conclusion</h3>
        <p><%= @preview.conclusion.html_safe %></p><hr>

        <h4><span class="glyphicon glyphicon-th-list"></span>&nbsp Related Topics</h4>
        <% @related_topics.each do |topic| %>
          <div id="related-topic">
            <h3 style="margin-top: 10px;"><%= link_to topic.title, admin_topic_path(topic) %></h3>
            <em><h5 style="margin-top: -5px; margin-bottom: 5px; color: #888"><%= topic.report_date %></h5></em>
            <%= truncate(topic.intro.gsub("<p>", ""), length: 250) %>
          </div>
        <% end %><hr>

        <h4>Tags</h4>
        <ul>
          <% @preview.tags.each do |tag| %>
            <li><%= tag.name %></li>
          <% end %>
        </ul><br>

        <%= button_to "Edit preview", edit_admin_preview_path(@preview), method: :get, class: "btn btn-control btn-success" %><br>
        <%= button_to "Delete preview", admin_preview_path(@preview), method: :delete, class: "btn btn-control btn-danger" %>
      </div>
    </div>

    <div class="column col-xs-3" id="sidebar">
      <div id="indicator-sidebar">
        <h4><span class="glyphicon glyphicon-eye-open"></span>&nbsp Visuals</h4>
        <table id="ind-side-table">
          <% @visuals.each do |visual| %>
          <tr>
            <% if visual == @visuals.last %>
              <td style="padding-top: 8px; border-bottom: none"><%= link_to visual.title, admin_visual_path(visual) %></td>
            <% elsif visual == @visuals.first %>
              <td style="padding-bottom: 8px; padding-top: 3px;"><%= link_to visual.title, admin_visual_path(visual) %></td>
            <% else %>
              <td style="padding-bottom: 8px; padding-top: 8px;"><%= link_to visual.title, admin_visual_path(visual) %></td>
            <% end %>
          </tr>
          <% end %>
        </table>
      </div>
      <div id="country-sidebar">
        <h4><span class="glyphicon glyphicon-globe"></span>&nbsp Related Countries</h4>
        <ul>
          <% @related_countries.each do |country| %>
            <li><%= link_to country.name, admin_country_path(country) %></li>
          <% end %>
        </ul>
      </div>
      <div id="indicator-sidebar">
        <h4><span class="glyphicon glyphicon-stats"></span>&nbsp Related Indicators</h4>
        <ul>
          <% @related_indicators.each do |indicator| %>
            <li><%= link_to indicator.name + " (" + indicator.countries.first.name + ")", admin_indicator_path(indicator) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>